services:
  app:
    build: .
    ports:
      - "3004:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=file:/app/data/prod.db
      - NODE_ENV=production
    volumes:
      - db-data:/app/data
    command: sh -c "npx prisma generate && npx prisma db push --skip-generate && node node_modules/.bin/next start"

volumes:
  db-data:
